// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Just Starting',
      collapsed: false,
      items: [
        'whats-new-list',
        'upgrading-from-v15',
        'v15-catalog-migration',
      ],
    },
    {
      type: 'category',
      label: 'WinBidPro 16',
      collapsed: false,
      items: [
        'sharing-jobs',
        'job-alerts',
        { type: 'autogenerated', dirName: 'glass' },
        { type: 'autogenerated', dirName: 'tool-tabs' },
        { type: 'autogenerated', dirName: 'components' },
        { type: 'autogenerated', dirName: 'shop-drawings-and-cad' },
      ],
    },
    {
      type: 'category',
      label: 'IT & Developers',
      items: [
        { type: 'autogenerated', dirName: 'setup' },
        { type: 'autogenerated', dirName: 'troubleshooting' },
        { type: 'autogenerated', dirName: 'third-party-exports' },
      ],
    },
  ],
};

module.exports = sidebars;
