// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  v16Sidebar: [{type: 'autogenerated', dirName: 'v16'}],
  v15Sidebar: [{type: 'autogenerated', dirName: 'v15'}],
};

export default sidebars;
